### ISSUE TITLE
关于平假字注音没有显示出来的问题

### ISSUE THREAD

**Issue by snakepat** [Eroge-Helper/ErogeHelper#10]
谢谢大佬在上一个issue问题上的解答，相关的问题几乎都解决了，但关于平假字注音的问题还是存在，希望大佬可以帮忙检查一下
![142b569df39f95266ca0ae223d92df1](https://user-images.githubusercontent.com/56012044/121763882-f2316b00-cb71-11eb-9401-7c88d8ca1cec.jpg)
![142b569df39f95266ca0ae223d92df1](https://user-images.githubusercontent.com/56012044/121763888-f5c4f200-cb71-11eb-998a-7e7d93fdbe1f.jpg)

**Comment by luojunyuan** [comment]
这个太离谱了。。我甚至不知道怎么复现这个情况，你可以试式改常规里的外部窗口？或者卸载，清除一下缓存（即删除分词字典），相当于重新设置一遍试试。如果你方便还可以联系我qq 1583440748

**Comment by snakepat** [comment]
大佬，这里显示我被拒绝添加了(ﾉ ○ Д ○)ﾉ　



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年6月12日(周六) 下午2:37
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Eroge-Helper/ErogeHelper] 关于平假字注音没有显示出来的问题 (#10)




 
这个太离谱了。。我甚至不知道怎么复现这个情况，你可以试式改常规里的外部窗口？或者卸载，清除一下缓存（即删除分词字典），相当于重新设置一遍试试。如果你方便还可以联系我qq 1583440748

**Comment by luojunyuan** [comment]
请先使用installer卸载缓存，重新安装打开程序后，在日文分词中选择此处提供的词典 [百度云](https://pan.baidu.com/s/1-7XVu_K4wuAWghsf9SjLPg) 提取码: xvmc （压缩包大小528mb）

以前的词典不能用了、此处是我没处理好。如果结果显示正常请点击下方的Close Issue

**Comment by snakepat** [comment]
谢谢大佬，确实解决了
