### ISSUE TITLE
Windows 11 中，右键通过 LE 启动游戏不调用 LE

### ISSUE THREAD

**Issue by ymd45921** [Eroge-Helper/ErogeHelper#14]
操作系统：Windows 11 Pro 22000.176
ErogeHelper 版本：0.0.8.2
LocaleEmulator 版本：2.5.0.1
视觉小说：さくら、もゆ。

描述：通过右键菜单选项”Eroge Helper > 使用 Locale Emulator 转区启动后“后游戏窗口仍然是乱码，在任务管理器中没有出现 `LEProc` 进程（LocaleEmulator 2.5.0.1 会在转区时创建一个 `LEProc` 进程），游戏会因为编码问题而退出。

在 Windows 10 21H1 的设备上使用同样的软件测试，没有出现同样的问题；在 Windows 10 和 Windows 11 中使用新版 Locale Emulator 第一次启动该游戏，Eroge Helper 都会报错一次”该进程被占用所以无法持有（类似意思）“的提示并且注入失败；第二次启动后不再提示并工作。

P.S. 可以提供截图（如果需要）

**Comment by ymd45921** [comment]
此外，在 Windows 11 下，如果仅使用 Locale Emulator 启动该游戏，再运行 `ErogeHelper.exe` 手动注入游戏，则 Locale Emulator 和 Eroge Helper 都正常工作。

**Comment by luojunyuan** [comment]
谢谢你的详细说明，造成这个的原因是因为LE前段时间刚更新win11支持。
将新版LE程序(2.5.0.1)文件夹下的
```
LocaleEmulator.dll
LoaderDll.dll
LEProc.exe
LEConfig.xml
LECommonLibrary.dll
```
替换到 `ErogeHelper/libs/x86` 应该可以恢复工作。

我想我会在下一次EH更新后修复这个（估计会很久以后了，好得EH用户量并不多）

**Comment by ymd45921** [comment]
感谢，这样做之后修复了！原来 ErogeHelper 是内置了 LE 嘛）作者加油！

为看到这个 issue 的人提供了一个已经整合过的版本：https://aoikaze-my.sharepoint.com/:u:/g/personal/i_aoikaze_onmicrosoft_com/EUlBsvsIPEVHmN1EEc8dWrUBRJ-n6OnxCoIGk7tC9L6G7g?e=sauJof

再次感谢您！
