### ISSUE TITLE
文本翻译

### ISSUE THREAD

**Issue by alcheholicon** [Eroge-Helper/ErogeHelper#5]
源文本过长导致翻译显示忽略过长文本怎么解决

**Comment by luojunyuan** [comment]
我写死了超过120个字符跳过不显示、既然这个会造成使用上的问题、之后会像vnr一样在设置里变得可以调整

**Comment by luojunyuan** [comment]
应该能在 v0.0.8 中调整了

如果还有问题请在下方回复我~
