### ISSUE TITLE
Unable to load DLL 'libs\texthostdll'or one of its dependencies

### ISSUE THREAD

**Issue by snakepat** [Eroge-Helper/ErogeHelper#9]
Unable to load DLL 'libs\texthostdll'or one of its dependencies: 找不到指定的模块
重新启动，重新解压，注册都没有，我之前在PC设备上成功了，但win板就出现这样的问题

**Comment by luojunyuan** [comment]
检查压缩包与程序目录下有没有 libs\texthost.dll 文件，可能是被杀毒软件删除了，请将该dll文件加入白名单

**Comment by snakepat** [comment]
之前检查过了，libs\texthost.dll文件确实还在，然后现在试了一下加白名单，但也失败了（不知道您看不看的到图像）
![2aa28c2161d5d2f3afa6a7f66c0cd4e](https://user-images.githubusercontent.com/56012044/121485054-6947f180-ca02-11eb-9253-03eeedf04a89.jpg)

**Comment by luojunyuan** [comment]
我看到你的文件目录显示的是0.0.6版本，有没有尝试最新的版本号是0.0.8.2可能已经修复了这个问题

**Comment by snakepat** [comment]
谢谢，但是有些不好意思，我GitHub用的不是很熟，不知道最新版本在哪里下载，只知道在Eroge-Helper/ErogeHelper下载code，恳求大佬指导






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Eroge-Helper/ErogeHelper"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月10日(星期四) 下午4:16
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Eroge-Helper/ErogeHelper] 我这里注入后会出现一个弹窗Unhandled UI Error (#9)





 
我看到你的文件目录显示的是0.0.6版本，有没有尝试最新的版本号是0.0.8.2可能已经修复了这个问题

**Comment by luojunyuan** [comment]
https://wws.lanzoui.com/ipcvhou7q2j

**Comment by snakepat** [comment]
谢谢，辛苦大佬了，我晚上有时间后试试




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Eroge-Helper/ErogeHelper"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月10日(星期四) 下午4:34
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Eroge-Helper/ErogeHelper] 我这里注入后会出现一个弹窗Unhandled UI Error (#9)





 
https://wws.lanzoui.com/ipcvhou7q2j

**Comment by snakepat** [comment]
&nbsp;大佬，还是遇到了相同的问题，不过这次有比较详细的解释，可是我看不懂（；´д｀）ゞ




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Eroge-Helper/ErogeHelper"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月10日(星期四) 下午4:34
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Eroge-Helper/ErogeHelper] 我这里注入后会出现一个弹窗Unhandled UI Error (#9)





 
https://wws.lanzoui.com/ipcvhou7q2j

**Comment by luojunyuan** [comment]
https://wws.lanzoui.com/ix35Yq152ed
密码:fpk2
https://wws.lanzoui.com/i1UfXq152od
密码:3anw

**Comment by snakepat** [comment]
谢谢大佬，我“大概”解决了打开的问题，但我遇到了一些bug，请允许我用图片说明：





1、从上往下，图一图二是我尝试专区运行Erewhon是遇到的问题，直接无法启动
2、图三图四是我运行イブニクル2时遇到的问题，只会显示一些类似UI界面的信息
3、图五是我运行極限痴漢特異点2时遇到的问题，暂时是什么都没有显示
其实我运行A社的母爛漫的时候是成功了，但不知道为什么没有在上方或下方显示平假字或片假字。
非常抱歉，给您添麻烦了，很感谢您之前耐心帮我解决问题。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Eroge-Helper/ErogeHelper"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月10日(星期四) 晚上11:17
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Eroge-Helper/ErogeHelper] 我这里注入后会出现一个弹窗Unhandled UI Error (#9)





 
https://wws.lanzoui.com/ix35Yq152ed
 密码:fpk2
 https://wws.lanzoui.com/i1UfXq152od
 密码:3anw

**Comment by luojunyuan** [comment]
你的图都不能看见、你需要用电脑在这个页面点击你回复的右上角三个点 “Edit” 编辑以下。

1. 我这边没问题，也可以不用转曲直接启动（游戏文本乱码，提取到的文本显示正常），尝试先不使用EH启动，使用LE能否启动，或者尝试一下勾选管理员身份运行（一般情况下都不需要勾选这个的）
2. 点击小圆点进入设置，选择钩子设置，选择重新注入游戏，选择system32，进行一下游戏文本，在下方方框中找到正确的文本，选择后提交。
3. 这个是unity引擎的游戏，支持得不好，EH没法用。
4. 母烂漫点小圆点，进入设置界面，日文分词，检查显示日文文本有未开启。检查钩子设，填入正则表达式`[$]{.*?}` 下方选择System43，提交。

**Comment by luojunyuan** [comment]
我关闭了这个issue，其他仍旧存在问题可以在下方继续留言~，对于新的问题也可以重新打开一个新的issue
